o Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
#PublicNetwork
  config.vm.network "public_network", ip: "192.168.0.101"

  # Provisioning:
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt update -y
    sudo apt install -y nginx
    sudo sed -i 's/listen 80 default_server;/listen 8082 default_server;/g' /etc/nginx/sites-available/default
    sudo sed -i 's/listen \\[::\\]:80 default_server;/listen [::]:8082 default_server;/g' /etc/nginx/sites-available/default
    echo "Welcome home, girl" | sudo tee /var/www/html/index.html
    sudo systemctl restart nginx
  SHELL
end
