apiVersion: apps/v1
kind: Deployment

metadata:
  name: mysql
  namespace: dev-ns

spec:
  replicas: 1

  selector:
    matchLabels:
      app: mysql

  template:
    metadata:
      labels:
        app: mysql

    spec:
      containers:
      - name: mysql

        image: mysql:8.0

        ports:
        - containerPort: 3306

        env:
        - name: MYSQL_ROOT_PASSWORD
          value: hard_passw0rd

        - name: MYSQL_DATABASE
          value: shop

        - name: MYSQL_USER
          value: petshop

        - name: MYSQL_PASSWORD
          value: hard_passw0rd

        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql

      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
                           