Vagrant.configure("2") do |config|

  # DB VM
  config.vm.define "db" do |db|
    db.vm.box = "bento/ubuntu-22.04"
    db.vm.network "private_network", ip: "192.168.56.10"
    db.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end
    db.vm.provision "shell", path: "provision/db.sh",
      env: {
        "DB_USER" => ENV['DB_USER'],
        "DB_PASS" => ENV['DB_PASS'],
        "DB_NAME" => ENV['DB_NAME']
      }
  end

  # APP VM
  config.vm.define "app" do |app|
    app.vm.box = "bento/ubuntu-22.04"
    app.vm.network "private_network", ip: "192.168.56.11"
    app.vm.network "forwarded_port", guest: 8080, host: 8080
    app.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end
    app.vm.provision "shell", path: "provision/app.sh",
     env: {
        "DB_HOST" => "192.168.56.10",
        "DB_PORT" => "3306",
        "DB_NAME" => ENV['DB_NAME'],
        "DB_USER" => ENV['DB_USER'], 
        "DB_PASS" => ENV['DB_PASS'],
        "APP_USER" => "app",
        "PROJECT_REPO" => ENV['PROJECT_REPO'],
        "APP_DIR" => "/home/app"
      }
  end

end