pipeline {
    agent any

    stages {
        stage('Build Docker image') {
            steps {
                sh 'docker build -t step-project-2 .'
            }
        }

        stage('Run tests') {
            steps {
                sh 'docker run step-project-2'
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh '''
                      docker login -u $DOCKER_USER -p $DOCKER_PASS
                      docker tag step-project-2 $DOCKER_USER/step-project-2:latest
                      docker push $DOCKER_USER/step-project-2:latest
                    '''
                }
            }
        }
    }
}


