pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                echo 'Code uploaded Jenkins'
            }
        }

        stage('Build Docker image') {
            steps {
                sh 'docker build -t step-project-2 .'
            }
        }

        stage('Run tests') {
            steps {
                sh 'docker run step-project-2'
            }
        }
    }
}

