global:
  resolve_timeout: 5m

route:
  receiver: telegram
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h

receivers:
  - name: telegram
    telegram_configs:
      - bot_token: "BOT_TOKEN"
        chat_id: CHAT_ID
        send_resolved: true
        parse_mode: HTML

        message: 
          🚨 <b>{{ .CommonLabels.alertname }}</b>

          <b>Instance:</b> {{ .CommonLabels.instance }}

          <b>Severity:</b> {{ .CommonLabels.severity }}

          <b>Description:</b>
          {{ .CommonAnnotations.description }}